//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludVida.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public byte[] photo { get; set; }
        public string documentType { get; set; }
        public string documentNumber { get; set; }
        public string names { get; set; }
        public string surnames { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public decimal height { get; set; }
        public decimal weight { get; set; }
        public string city { get; set; }
        public System.DateTime birthDate { get; set; }
        public decimal imc { get; set; }
    }
}
